directs/urls.py
"""Directs URLs."""

# Django
from django.urls import path

# Views
# Aqui se habia definido como as post_views. Pero ya no es necesario.
from directs import views

urlpatterns = [
    # Managment
    path(
        route='inbox/',
        view=views.inbox,
        name='message'
    ),  # Agregaremos una vista de la app "directs" para el inbox

    path(
        route='directs/<str:username>/',
        view=views.directs,
        name='direct'
    ),  # Agregaremos una vista de la app "directs" para chat personal

    path(
        route='send/',
        view=views.SendMessage,
        name='sendMessage'
    ),  # Agregaremos una vista de la app "directs" para enviar mensajes

    path(
        route='search/',
        view=views.UserSearch,
        name='userSearch'
    ),  # Agregaremos una vista de la app "directs" para buscar un usuario

    path(
        route='new/<str:username>',
        view=views.NewMessage,
        name='newMessage'
    ),  # Agregaremos una vista de la app "directs" para crear un nuevo mensajes

    path(
        route='delete/<str:username>',
        view=views.DeleteMessage,
        name='deleteMessage'
    ),  # Agregaremos una vista de la app "directs" para eliminar conversacion actual.

]

platzigram/urls.py
# Django
from django.contrib import admin
from django.conf import settings # Importamos la libreria de "settings" para poder mostrar imagenes.
from django.conf.urls.static import static # Libreria para poder serviri imagenes en desarrollo.
from django.urls import path, include
# urls.py
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include(('posts.urls','posts'), namespace='posts')), # En la tupla incluimos al modulo "posts.urls" y la app "posts".
    path('users/', include(('users.urls','users'), namespace='users')), # En la tupla incluimos al modulo "users.urls" y la app "users".
    path('comment/', include(('comment.urls','comment'), namespace='comment')), # En la tupla incluimos al modulo "comment.urls" y la app "comment".
    path('message/', include(('directs.urls','directs'), namespace='directs')), # En la tupla incluimos al modulo "directs.urls" y la app "directs".
    path('notifications/', include(('notifications.urls','notifications'), namespace='notifications')), # En la tupla incluimos al modulo "notifications.urls" y la app "notifications".
    
    
    #Password reset
    path(route='password_reset/', view=auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
# Aqui se habia definido como as post_views. Pero ya no es necesario.
from posts import views

urlpatterns = [

    # Managment
    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),  # Agregaremos una vista de la app "posts"

    path(
        route='posts/new',
        view=views.CreatePostView.as_view(),
        name="create"
    ),  # Agregamos la vista para crear un nuevo post.

    # Solucion del reto por parte del profe

    path(
        route='posts/<int:pk>/',  # post.id, pk
        view=views.PostDetailView.as_view(),
        name='detailPost'
    ),

    path(
        route='posts/<int:post_id>/like',
        view=views.LikesView,
        name="postLike"
    ),

    path(
        route='posts/<int:post_id>/update',
        view=views.UpdatePostView.as_view(),
        name="postUpdate"
    ),

    path(
        route='posts/<int:pk>/delete',
        view=views.PostDeleteView.as_view(),
        name="postDelete"
    ),

    path(
        route='posts/<int:pk>/<int:id>/comment_delete',
        view=views.DeleteCommentView.as_view(),
        name="commentDelete"
    ),

    path(
        route='posts/<int:post_pk>/<int:comments_id>/update_comment',
        view=views.UpdateCommentView.as_view(),
        name="commentUpdate"
    ),

]

users/urls.py
"""Users URLs."""

# Django
from django.urls import path


# Views
# Aqui se habia definido como as user_views. Pero ya no es necesario.
from users import views

urlpatterns = [
    
    # Managment
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),  # Agregamos la vista para ingresar a la app.
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),  # Agregamos la vista para salir de la app.
    path(
        route='signup/',
        view=views.SignUpView.as_view(),
        name="signup"
    ),  # Agregamos la vista para registrarse en la app.
    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name="update"
    ),  # Agregamos la vista para modificar nuestro perfil.

    path(
        route='me/profile/delete_photo',
        view=views.delete_picture,
        name="deletePicture"
    ),  # Agregamos la vista para eliminar nuestra foto de perfil.

    # Posts
    path(
        route='profile/<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    path(
        route='profile/<str:username>/follow',
        view=views.FollowView,
        name="follow"
    ),

    path(
        route='profile/<str:username>/followers',
        view=views.FollowerView.as_view(),
        name="followers"
    ),

    path(
        route='profile/<str:username>/following',
        view=views.FollowingView.as_view(),
        name="following"
    ),

    path(
        route='me/profile/delete_profile',
        view=views.delete_user,
        name="deleteUser"
    )  # Agregamos la vista para eliminar nuestro perfil y usuario.



]

directs/models.py
# Django.
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Max

# Create your models here.


class Message(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user")
    sender = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="from_user")
    reciepient = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="to_user")
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):  # Definimo que mostrar al ejecutar un QUERRY
        return '{} by @{},s:{},r:{}'.format(self.body, self.user.username, self.sender, self.reciepient)

    def send_message(from_user, to_user, body):
        # Sender message function.
        sender_message = Message(
            user=from_user,
            sender=from_user,
            reciepient=to_user,
            body=body,
            is_read=True
        )
        sender_message.save()

        # Recipient message function.
        reciepient_message = Message(
            user=to_user,
            sender=from_user,
            reciepient=from_user,
            body=body,
            is_read=False
        )
        reciepient_message.save()

        return sender_message

    def get_message(user):
        users = []
        messages = Message.objects.filter(user=user, body__isnull=False, body__gt='').values(
            "reciepient").annotate(last=Max('date')).order_by("-last")
        for message in messages:

            users.append({
                'user': User.objects.get(pk=message['reciepient']),
                'last': message['last'],
                'unread': Message.objects.filter(user=user, body__isnull=False, body__gt='', reciepient__pk=message['reciepient'], is_read=False).count()

            })

        return users

directs/views.py
# Django
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.paginator import Paginator
from django.db.models import Q

# Models
from directs.models import Message
from django.contrib.auth.models import User

# Create your views here.


@login_required
def inbox(request):
    user = request.user  # Obtenemos al usuario actual.
    # Obtenemos todos los mensajes asociados al usuario actual.
    messages = Message.get_message(user=user)
    # Esta variable se utiliza para indicar con que usuario estamos hablando.
    active_direct = None
    # Esta variable guarda los mensajes asociados a la varibale anterior.
    directs = None

    context = {
        'directs': directs,
        'active_direct': active_direct,
        'messages': messages,
        'unread_notifi': request.unread_notifi
    }
    
    return render(request, 'directs/inbox.html', context)


@login_required
def directs(request, username):
    user = request.user  # Obtenemos al usuario logeado
    # Obtenemos una lista de "users", "messages" y un contador que devuelve "get_message"
    messages = Message.get_message(user=user)
    # Definimos al usuario recipient con el "username" proporcionado por la URL/request.
    active_direct = username
    recipient = User.objects.get(username=active_direct)
    # Obtenemos todos los mensajes relacionados principalmente con el usuario actual y con el usuario del recipiente.
    directs = Message.objects.filter(user=user, reciepient__username=username)
    directs.update(is_read=True)  # Actualizamos el no leido a leido.

    for message in messages:
        # El request nos envia un username "que hemos seleccionado" y lo compara con el "recepient".
        if message['user'].username == username or user.username == active_direct:
            message['unread'] = 0  # Actualizamos el dato de no leidos a 0.

    context = {
        'directs': directs,
        'active_direct': active_direct,
        'messages': messages,
        'unread_notifi': request.unread_notifi,
        'recipient': recipient
    }

    return render(request, 'directs/directs.html', context)


@login_required
def SendMessage(request):
    # Obtenemos al usuario logeado y lo guardamos en "from_user".
    from_user = request.user
    # Obtenemos al "remitente/username" que nos envia el form en el campo "to_user".
    to_user_username = request.POST.get('to_user')
    # Obtenemos al "mensaje" que nos envia el form en el campo "body".
    body = request.POST.get('body')
    # print("SendMessage")
    if request.method == "POST":  # Tambien, al recibir el form, pasa lo siguiente:
        # Definimos al campo "to_user/remitente" como obj "User" mediante "to_username"
        to_user = User.objects.get(username=to_user_username)
        # Llamamos a la función "send_message" con los campos obtenidos anteriormente.
        Message.send_message(from_user, to_user, body)
        # Construimos una "URL" con reverse.
        redirect_url = reverse('directs:direct', args=[to_user_username])

        context = {
            'unread_notifi': request.unread_notifi
        }
        # Y redirigimos a "url direct" que es el chat personal.
        return redirect(redirect_url, context)
    else:
        pass  # No hagas algo


@login_required
def UserSearch(request):
    query = request.GET.get('q')
    context = {'unread_notifi': request.unread_notifi}

    if query:
        users = User.objects.filter(Q(username__icontains=query))
        # Paginator
        paginator = Paginator(users, 8)
        page_number = request.GET.get('page')
        users_paginator = paginator.get_page(page_number)

        context = {
            'users': users_paginator,
            'unread_notifi': request.unread_notifi
        }
        
    return render(request, 'directs/search.html', context)


@login_required
def NewMessage(request, username):
    from_user = request.user
    body = ""
    try:
        to_user = User.objects.get(username=username)
    except Exception as e:
        return redirect("directs:userSearch")
    if from_user != to_user:
        Message.send_message(from_user, to_user, body)
    redirect_url = reverse('directs:direct', args=[to_user])
    context = {'unread_notifi': request.unread_notifi}
    
    return redirect(redirect_url, context)


@login_required
def DeleteMessage(request, username):
    user = request.user
    # print("eliminacion de perfil1")
    reciepient = User.objects.get(username=username)
    if request.method == 'POST':
        messages = Message.objects.filter(user=user, reciepient=reciepient)
        messages.delete()
        
        return redirect('directs:message')  # Reemplaza con tu URL de inicio
    
    context = {
        'unread_notifi': request.unread_notifi,
        'recipient': reciepient
    }
    
    return render(request, 'directs/delete_message.html', context)

templates/directs/delete_message.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
    <title>@{{ request.user.username }} | Delete conversation</title>
{% endblock  %}

{% block container %}

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6 pt-3 pb-3" id="profile-box">
            <h5 class="card-title">Delete the current conversation?</h5>
            <p class="card-text">Deleting a conversation will permanently delete it from the database.</p>
            <form class='col-md-12  d-flex justify-content-between  ' method="POST" action="">
                {% csrf_token %}
                <a class="btn btn-primary" href="{% url "directs:direct" recipient.username %}">Keep conversation</a>
                <button type="submit" class="btn btn=primary btn-danger">Delete conversation</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/directs/directs.html
{% extends 'base.html' %} 
{% load static %} 
{% load humanize %} 
{% block head_content %}
  <title>@{{ user.username }} | Messages</title>
  <!-- Bootstrap CSS -->
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
  />
  <!-- Font Awesome CSS -->
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
  />
  <!-- jQuery y Popper.js -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <!-- Bootstrap JS -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous"
  />
<style>
  body {
    margin-top: 20px;
  }

  .chat-online {
    color: #34ce57;
  }

  .chat-offline {
    color: #e4606d;
  }

  .chat-messages {
    display: flex;
    flex-direction: column;
    max-height: 800px;
    overflow-y: scroll;
  }

  .chat-message-left,
  .chat-message-right {
    display: flex;
    flex-shrink: 0;
  }

  .chat-message-left {
    margin-right: auto;
  }

  .chat-message-right {
    flex-direction: row-reverse;
    margin-left: auto;
  }
  .py-3 {
    padding-top: 1rem !important;
    padding-bottom: 1rem !important;
  }
  .px-4 {
    padding-right: 1.5rem !important;
    padding-left: 1.5rem !important;
  }
  .flex-grow-0 {
    flex-grow: 0 !important;
  }
  .border-top {
    border-top: 1px solid #dee2e6 !important;
  }
</style>
{% endblock %} 

{% block container %}

<div class="container mt-3">
  <h1 class="h3 mb-3">Messages</h1>
  <div class="card">
    <div class="d-flex justify-content-center">
      <div
        class="col-xl-3 border-right chat-messages overflow-auto"
        style="max-height: 300px; height: 300px; max-width:300px;"
      >
        <div class="px-4 d-none d-md-block">
          <div class="d-flex align-items-center">
            <div class="flex-grow-1 d-flex justify-content-center">
              <a
                href="{% url 'directs:userSearch' %}"
                class="btn btn-success mt-4 mb-4"
                >New Message</a
              >
            </div>
          </div>
        </div>
        {% for message in messages %}
          <a
            href=" {% url 'directs:direct' message.user.username %} "
            class="list-group-item list-group-item-action border-0 {% if active_direct == message.user.username %}active{% endif %}"
          >
            <div class="badge bg-success float-right"></div>
            <div class="d-flex align-items-start pb-2">
              {% if message.user.profile.picture %}
                <img
                  src="{{ message.user.profile.picture.url }}"
                  class="rounded-circle mr-1"
                  alt="img"
                  width="40"
                  height="40"
                />
              {% else %}
                <img
                  src="{% static 'img/default-profile.png' %}"
                  class="rounded-circle mr-1"
                  alt="img"
                  width="40"
                  height="40"
                />

              {% endif %}

              <div class="flex-grow-1 ml-6">
                <b>{{message.user.first_name}} {{message.user.last_name}}</b>
                <div class="small">
                  <span class="fas fa-circle chat-online"></span>
                  @{{message.user.username}}
                </div>
                {% if message.unread > 0 %}
                  <div class="small">
                    <span class="fas fa-circle chat-online"></span>
                    {{message.unread}} new messages
                  </div>
                {% endif %}
              </div>
            </div>
          </a>
        {% endfor %}

        <hr class="d-block d-lg-none mt-1 mb-0" />
      </div>
      <div class="col-12 col-lg-7 col-xl-9" id = "directs">
        <div class="py-2 px-4 border-bottom d-none d-lg-block" id = "directs1">
          <div class="d-flex justify-content-between py-1">
            <div class="d-flex mr-2">
              {% if recipient.profile.picture %}
                <img
                  src="{{ recipient.profile.picture.url }}"
                  class="rounded-circle mr-1"
                  alt="img"
                  width="55"
                  height="55"
                />
              {% else %}
                <img
                  src="{% static 'img/default-profile.png' %}"
                  class="rounded-circle mr-1"
                  alt="img"
                  width="55"
                  height="55"
                />
              {% endif %}
              <div class="d-flex align-items-center">
                <b
                  ><span class="fas fa-circle chat-online"></span>
                  {{recipient.first_name}} {{recipient.last_name}}</b
                >
              </div>
            </div>

            <div class="d-flex">
              <div id="directs2">
                <button class="btn btn-primary btn-lg mr-1 px-3">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="feather feather-phone feather-lg"
                  >
                    <path
                      d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"
                    ></path>
                  </svg>
                </button>
                <button
                  class="btn btn-info btn-lg mr-1 px-3 d-none d-md-inline-block"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="feather feather-video feather-lg"
                  >
                    <polygon points="23 7 16 12 23 17 23 7"></polygon>
                    <rect
                      x="1"
                      y="5"
                      width="15"
                      height="14"
                      rx="2"
                      ry="2"
                    ></rect>
                  </svg>
                </button>
              </div>
              <ul class="navbar-nav">
                <li
                  class="nav-item dropdown btn btn-light border btn-lg px-3 ml-1"
                >
                  <a
                    class="nav-link p-0"
                    href="#"
                    id="navbarDropdown"
                    role="button"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false"
                  >
                    <i class="fas fa-ellipsis-h" style="color: gray"></i>
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a
                      class="dropdown-item"
                      href="{% url 'directs:deleteMessage' recipient.username  %}"
                      >Delete</a
                    >
                    <a
                      class="dropdown-item"
                      href="{% url 'users:detail' recipient.username   %}"
                      >View Profile</a
                    >
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <div class="position-relative">
          <div
            class="chat-messages p-4 overflow-auto"
            style="max-height: 300px; height: 300px"
          >
            {% for direct in directs %} 
              {% if direct.body != "" %} 
                {% if direct.sender == request.user %}
                  <div class="chat-message-right pb-2">
                    <div>
                      <a href="">
                        {% if direct.sender.profile.picture %}
                          <img
                          src="{{ direct.sender.profile.picture.url }}"
                          class="rounded-circle mr-1"
                          alt="img"
                          width="40"
                          height="40"
                          />
                        {% else %}
                          <img
                          src="{% static 'img/default-profile.png' %}"
                          class="rounded-circle mr-1"
                          alt="img"
                          width="40"
                          height="40"
                          />
                        {% endif %}
                      </a>  
                      <div
                        class="text-muted small text-nowrap mt-2"
                        style="font-size: 10px; color: rgba(180, 180, 180, 0)"
                      >
                        <p style="font-size: 10px; color: black">
                          {{direct.date|naturaltime}}
                        </p>
                      </div>
                    </div>
                    <div class="flex-shrink-1 bg-light rounded py-2 px-3 ml-3">
                      <!-- <div class="font-weight-bold mb-1">Sharon Lessman</div> -->
                      {{direct.body}}
                    </div>
                  </div>
                {% else %}
                  <div class="chat-message-left pb-2">
                    <div>
                      <a href="">
                        {% if direct.sender.profile.picture  %}
                          <img
                              src="{{ direct.sender.profile.picture.url }}"
                              class="rounded-circle mr-1"
                              alt="img"
                              width="40"
                              height="40"
                          />
                        {% else %}
                          <img
                            src="{% static 'img/default-profile.png' %}"
                            class="rounded-circle mr-1"
                            alt="img"
                            width="55"
                            height="55"
                          />
                        {% endif %}
                      </a>
                      <div
                        class="text-muted small text-nowrap mt-2"
                        style="font-size: 10px; color: rgba(180, 180, 180, 0)"
                      >
                        <p style="font-size: 10px; color: black">
                          {{direct.date|naturaltime}}
                        </p>
                      </div>
                    </div>
                    <div class="flex-shrink-1 bg-light rounded py-2 px-3 ml-3">
                      <!-- <div class="font-weight-bold mb-1">Sharon Lessman</div> -->
                      {{direct.body}}
                    </div>
                  </div>
              {% endif %} 
            {% endif %} 
        {% endfor %}
          </div>
        </div>

        <div class="flex-grow-0 py-3 px-4 border-top">
          <form method="POST" action=" {% url 'directs:sendMessage' %} ">
            {% csrf_token %}
            <div class="input-group">
              <input
                type="hidden"
                name="to_user"
                id=""
                value="{{active_direct}}"
              />
              <input
                name="body"
                type="text"
                class="form-control"
                placeholder="Type your message"
                required
              />
              <button class="btn btn-primary" type="submit">Send</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

{% endblock container %}

templates/directs/search.html
{% extends 'base.html' %}
{% load static %}

{% block head_content %}
  <title>@{{ user.username }} | Search</title>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
{% endblock %}

{% block container %}
  <div id="wrapper">
    <div class="container mt-5  d-flex justify-content-center ">
      <div class="phone-app-ddemo"></div>
        <div class="form-data ">

          <form action="" method="GET">
            <div class="headedr__search" style="margin-left:2rem;">
                <input type="text" placeholder="Search" name="q" value="{{ request.GET.q }}" required>
                <button class="btn btn-primary" type="submit">Search</button>                
            </div>
          </form>

          <form action="" method="POST" enctype="multipart/form-data">
            <div class="logo">
              <h3 style="padding-top: 5px; font-size: 20px;">Search Results</h3>
            </div>

          {% for user in users %}
            {% if  user != request.user%}
              <div class="side-menu__user-profile d-flex align-items-center justify-content-start " style="text-align: start; border: solid rgba(192, 192, 192, 0.514) 1px; padding: 10px; border-radius: 25px; width:25vw;">
                <a href=" {% url 'users:detail' user.username %} " class="side-menu__user-avatar">
                  {% if user.profile.picture %}
                      <img src="{{ user.profile.picture.url }}" alt="User Picture" class="rounded-circle" width="100px" height="100px">
                  {% else %}
                      <img src="{% static 'img/default-profile.png' %}" alt="User Picture default" class="rounded-circle" width="100px" height="100px">
                                              
                  {% endif %}
                </a>
                <div class="side-menu__user-idnfo ml-3">
                    {% if user.first_name %}
                      <strong href="{% url 'users:detail' user.username %}" style="font-size: 15px; color: black; text-align: center;">{{user.first_name|title }} {{user.last_name|title }}</strong>
                    {% else%}
                      <strong href="">Instagram User</strong>

                    {% endif %}
                    <br>
                    <span style="font-size: 14px;">@{{user.username}}</span>
                    <br>
                    <a href="{% url 'users:detail' user.username %}" {#style="color: blue;"#} class="btn btn-sm btn-outline-info">View Profile</a>
                    <br>
                    <a
                        href="{% url "directs:newMessage" user.username %}"
                        class="btn btn-sm btn-outline-info mt-1"
                    >
                        New message
                    </a>
                </div>
              </div>
            {% endif %}
        {% endfor %} 
        </form>
      </div>
    </div>
    
    <footer class="footer mt-auto py-2">
        <div class="container text-center" style="margin-top:26rem;">
            <span class="text-muted">© 2024 Platzigram</span>
        </div>
    </footer>

  </div>

{% endblock container %}