platzigram/urls.py
# Django
from django.contrib import admin
from django.conf import settings # Importamos la libreria de "settings" para poder mostrar imagenes.
from django.conf.urls.static import static # Libreria para poder serviri imagenes en desarrollo.
from django.urls import path, include
# urls.py
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include(('posts.urls','posts'), namespace='posts')), # En la tupla incluimos al modulo "posts.urls" y la app "posts".
    path('users/', include(('users.urls','users'), namespace='users')), # En la tupla incluimos al modulo "users.urls" y la app "users".
    path('comment/', include(('comment.urls','comment'), namespace='comment')), # En la tupla incluimos al modulo "comment.urls" y la app "comment".
    path('message/', include(('directs.urls','directs'), namespace='directs')), # En la tupla incluimos al modulo "directs.urls" y la app "directs".
    path('notifications/', include(('notifications.urls','notifications'), namespace='notifications')), # En la tupla incluimos al modulo "notifications.urls" y la app "notifications".
    
    
    #Password reset
    path(route='password_reset/', view=auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
# Aqui se habia definido como as post_views. Pero ya no es necesario.
from posts import views

urlpatterns = [

    # Managment
    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),  # Agregaremos una vista de la app "posts"

    path(
        route='posts/new',
        view=views.CreatePostView.as_view(),
        name="create"
    ),  # Agregamos la vista para crear un nuevo post.

    # Solucion del reto por parte del profe

    path(
        route='posts/<int:pk>/',  # post.id, pk
        view=views.PostDetailView.as_view(),
        name='detailPost'
    ),

    path(
        route='posts/<int:post_id>/like',
        view=views.LikesView,
        name="postLike"
    ),

    path(
        route='posts/<int:post_id>/update',
        view=views.UpdatePostView.as_view(),
        name="postUpdate"
    ),

    path(
        route='posts/<int:pk>/delete',
        view=views.PostDeleteView.as_view(),
        name="postDelete"
    ),

    path(
        route='posts/<int:pk>/<int:id>/comment_delete',
        view=views.DeleteCommentView.as_view(),
        name="commentDelete"
    ),

    path(
        route='posts/<int:post_pk>/<int:comments_id>/update_comment',
        view=views.UpdateCommentView.as_view(),
        name="commentUpdate"
    ),

]

users/urls.py
"""Users URLs."""

# Django
from django.urls import path


# Views
# Aqui se habia definido como as user_views. Pero ya no es necesario.
from users import views

urlpatterns = [
    
    # Managment
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),  # Agregamos la vista para ingresar a la app.
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),  # Agregamos la vista para salir de la app.
    path(
        route='signup/',
        view=views.SignUpView.as_view(),
        name="signup"
    ),  # Agregamos la vista para registrarse en la app.
    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name="update"
    ),  # Agregamos la vista para modificar nuestro perfil.

    path(
        route='me/profile/delete_photo',
        view=views.delete_picture,
        name="deletePicture"
    ),  # Agregamos la vista para eliminar nuestra foto de perfil.

    # Posts
    path(
        route='profile/<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    path(
        route='profile/<str:username>/follow',
        view=views.FollowView,
        name="follow"
    ),

    path(
        route='profile/<str:username>/followers',
        view=views.FollowerView.as_view(),
        name="followers"
    ),

    path(
        route='profile/<str:username>/following',
        view=views.FollowingView.as_view(),
        name="following"
    ),

    path(
        route='me/profile/delete_profile',
        view=views.delete_user,
        name="deleteUser"
    )  # Agregamos la vista para eliminar nuestro perfil y usuario.



]

posts/models.py
"""Posts models."""
# Django
from django.db import models
from django.db.models.signals import post_save, post_delete

# Models
from django.contrib.auth.models import User
from notifications.models import Notification


class Post(models.Model):
    """Post model."""
    user = models.ForeignKey(
        User, on_delete=models.CASCADE)  # Relacionamos mediante la "foreignkey" al modelo User "ADMIN".
    # Relacionamos mediante la "foreignkey" al modelo Profile.
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)

    title = models.CharField(max_length=255)  # Creamos al campo del titulo.
    # Creamos el campo y ruta de almacenamiento de las fotos.
    photo = models.ImageField(upload_to='post/photos')

    # Creamos los campos para la fecha de creación.
    created = models.DateTimeField(auto_now_add=True)
    # Creamos los campos para la fecha de modificación
    modified = models.DateTimeField(auto_now=True)
    # Agregamos una variable que serivrá como contador de likes.
    likes = models.IntegerField(default=0)

    def __str__(self):  # Definimos que mostrar al ejecutar un QUERRY
        """Return title and username."""
        return '{} by @{} likes:{}'.format(self.title, self.user.username, self.likes)


class Like(models.Model):
    # Fk para el modelo User.
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_likes")
    # Fk para el modelos Posts.
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="post_likes")

    def user_liked_post(sender, instance, *args, **kwargs):
        like = instance
        sender = like.user
        post = like.post

        notify = Notification(post=post, sender=sender,
                              user=post.user, notification_type=1)
        notify.save()

    def user_unlike_post(sender, instance, *args, **kwargs):
        like = instance
        sender = like.user
        post = like.post

        notify = Notification.objects.filter(
            post=post, sender=sender, notification_type=1)
        notify.delete()


# Like model
post_save.connect(Like.user_liked_post, sender=Like)
post_delete.connect(Like.user_unlike_post, sender=Like)


# NOTAS:
# Models es un módulo en Django que proporciona herramientas y clases para definir la estructura de
# la base de datos mediante modelos
# Model es una clase base proporcionada por Django que se utiliza para definir modelos de datos (tablas).
# EmailField, CharField...son los tipos de datos que tendran cada columna.
# Reestructuraremos al modelo POST

posts/forms.py
"""Post forms."""
# Django
from django import forms

# Models
from posts.models import Post

"""Esta es otra forma de crear modelos (ModelForm)"""


class PostForm(forms.ModelForm):
    """Post model form."""
    class Meta:
        """Form settings"""
        model = Post
        fields = ('user', 'profile', 'title', 'photo')

posts/views.py
"""Posts views."""

# Django
# Decorador para mostrar contenido si estamos logeados.
from django.contrib.auth.decorators import login_required
from django.shortcuts import render  # Ahora si utilizaremos render Modulo para asefurar las classes de vistas.
from django.contrib.auth.mixins import LoginRequiredMixin
# Se utiliza para crear vistas que rendericen una lista de objetos desde una base de datos, como por ejemplo, mostrar una lista de usuarios, publicaciones de un blog
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404

# Forms
from posts.forms import PostForm
from comment.forms import CommentForm

# Model
from posts.models import Post, Like
from comment.models import Comment
from users.models import Profile
from django.contrib.auth.models import User

# Create your views here.


class PostsFeedView(LoginRequiredMixin, ListView):  # Clase para la paginacion.
    """Return all published posts."""
    template_name = 'posts/feed.html'
    model = Post
    ordering = ('-created',)
    paginate_by = 20
    context_object_name = 'post'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        # Obtener datos de otro modelo (en este caso, Like)
        likes = Like.objects.filter(user=self.request.user)
        # Filtrar likes del usuario actual
        # Aqui ingresamos a la "id" del modelo "Post" mediante la fk.
        liked_posts = [like.post.id for like in likes]
        # liked_posts = [like.post_id for like in likes] #Ambos funcionan "aqui ingresamos directamente al valor post_id del modelo likes"

        # Obtener comentarios para cada post en la lista
        comment_counts = {}
        for post in context['post']:
            comments = Comment.objects.filter(post=post)
            comment_counts[post.id] = comments.count()

        # print(comment_counts)
        context['comment_counts'] = comment_counts
        # Esto es para saber si el usuario actual ya dio like
        context['liked_posts'] = liked_posts
        context['unread_notifi'] = self.request.unread_notifi

        return context


class PostDetailView(LoginRequiredMixin, DetailView):
    """Return detail posts."""
    template_name = 'posts/detail.html'
    queryset = Post.objects.all()
    context_object_name = 'post'
    slug_field = 'pk' # Actua como una PK ya que no hay usuarios repetidos.
    slug_url_kwarg = 'pk' # Es el valor que se le agergará en cada campo al buscar un perfil.

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Obtener datos de otro modelo (en este caso, Like)
        likes = Like.objects.filter(user=self.request.user)
        # Filtrar likes del usuario actual
        liked_posts = [like.post.id for like in likes]
        # Obtenemos los comentarios de cada post
        post = self.get_object()  # Cachamos al objecto actual llamado post
        comment = Comment.objects.filter(post=post).order_by("-date")
        users_names = [names.user.username for names in comment]
        users_filter = User.objects.filter(username__in=users_names)
    
        context['liked_posts'] = liked_posts
        context['comment_form'] = CommentForm(initial={'user': self.request.user})
        context['comment'] = comment
        context['comment_count'] = comment.count()
        context['users_filter'] = users_filter
        context['unread_notifi'] = self.request.unread_notifi

        return context

    def post(self, request, *args, **kwargs):
        # post = get_object_or_404(Post, pk=self.kwargs['pk'])
        post = self.get_object()
        # print("bandera 1")
        comment_form = CommentForm(request.POST)
        # print("bandera 2")
        if comment_form.is_valid():
            # print("bandera 3")
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.user = request.user
            new_comment.save()
            return HttpResponseRedirect(reverse('posts:detailPost', args=[str(post.id)]))
        # print("bandera 4")

        context = self.get_context_data(**kwargs)
        context['comment_form'] = comment_form

        return render(request, 'post/detail.html', context)


class DeleteCommentView(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = 'posts/delete_comment.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('posts:detailPost', kwargs={'pk': pk})

    def get_object(self, queryset=None):
        pk = self.kwargs['pk']
        id = self.kwargs['id']
        comment = Comment.objects.get(post=pk, id=id)
        return comment

    def get_context_data(self, **kwargs):
        """Add user's posts to context."""
        context = super().get_context_data(**kwargs)
        context['unread_notifi'] = self.request.unread_notifi
        return context


class UpdateCommentView(LoginRequiredMixin, UpdateView):
    """Update comment view."""
    template_name = 'posts/update_comment.html'
    model = Comment
    fields = ['body']

    def get_object(self, queryset=None):
        post_pk = self.kwargs.get('post_pk')
        comments_id = self.kwargs.get('comments_id')
        post = Post.objects.get(id=post_pk)
        comment = Comment.objects.get(post=post, id=comments_id)
        return comment

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_pk = self.kwargs.get('post_pk')
        context['post'] = Post.objects.get(id=post_pk)
        context['unread_notifi'] = self.request.unread_notifi
        return context

    def get_success_url(self):
        post_pk = self.kwargs['post_pk']
        return reverse('posts:detailPost', kwargs={'pk': post_pk})


class CreatePostView(LoginRequiredMixin, CreateView):
    """Create a new post."""
    template_name = 'posts/new.html'
    form_class = PostForm
    success_url = reverse_lazy('posts:feed')

    def get_context_data(self, **kwargs):
        """Add user and profile to context."""
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        context["profile"] = self.request.user.profile
        context['unread_notifi'] = self.request.unread_notifi
        return context


class UpdatePostView(LoginRequiredMixin, UpdateView):
    """Update profile view."""
    template_name = 'posts/update_posts.html'
    model = Post
    fields = ['photo', 'title']

    def get_object(self, queryset=None):
        post_id = self.kwargs.get('post_id')
        return get_object_or_404(Post, pk=post_id, user=self.request.user)

    def get_success_url(self):
        """Creamos la "URL" con el nombre de usuario obtenido en la  linea anterior."""
        post_id = self.object.id
        return reverse('posts:postUpdate', kwargs={'post_id': post_id},)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['unread_notifi'] = self.request.unread_notifi
        return context


class PostDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'posts/delete_post.html'
    model = Post
    success_url = reverse_lazy('users:detail')
    slug_field = 'pk'
    slug_url_kwarg = 'pk'

    def get_queryset(self):
        # Filtra los posts solo del usuario actual
        return Post.objects.filter(user=self.request.user)

    def get_success_url(self):
        username = self.request.user.username
        return reverse_lazy('users:detail', kwargs={'username': username})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Agrega cualquier contexto adicional que necesites
        context['unread_notifi'] = self.request.unread_notifi

        return context


@login_required
def LikesView(request, post_id):
    user = request.user  # Identificamos al usuario actual.
    post = Post.objects.get(id=post_id)  # Obtenemos el post actual.
    current_likes = post.likes  # Verificamos cuantos likes tiene el post.
    liked = Like.objects.filter(user=user, post=post).count()

    if not liked:
        liked = Like.objects.create(user=user, post=post)
        # liked.save() # Esto estaba guardando dos veces una instancia Like.
        current_likes = current_likes + 1
    else:
        liked = Like.objects.filter(user=user, post=post).delete()
        current_likes = current_likes - 1

    post.likes = current_likes
    post.save()

    return HttpResponseRedirect(reverse('posts:feed'))

templates/posts/delete_comment.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
    <title>@{{ request.user.username }} | Delete comment</title>
{% endblock  %}

{% block container %}

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6 pt-3 pb-3" id="profile-box">
            <h5 class="card-title">Delete comment?</h5>
            <p class="card-text">Deleting a comment will permanently delete it from the database.</p>
            <form class='col-md-12  d-flex justify-content-between  ' method="POST" >
                {% csrf_token %}
                <a class="btn btn-primary" href="{% url "posts:detailPost" object.post.id %}">Keep comment</a>
                <button type="submit" class="btn btn=primary btn-danger">Delete comment</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/posts/delete_post.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
    <title>@{{ request.user.username }} | Delete post</title>
{% endblock  %}

{% block container %}

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6 pt-3 pb-3" id="profile-box">
            <h5 class="card-title">Delete Post?</h5>
            <p class="card-text">Deleting a post will permanently delete it from the database.</p>
            <form class='col-md-12  d-flex justify-content-between  ' method="POST" action="{% url 'posts:postDelete' post.id %}">
                {% csrf_token %}
                <a class="btn btn-primary" href="{% url "users:detail" post.user.username %}">Keep Post</a>
                <button type="submit" class="btn btn=primary btn-danger">Delete Post</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/posts/detail.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
    <title>@{{ user.username }} | Detail post</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <script src="https://kit.fontawesome.com/d2b20da030.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <!-- jQuery y Popper.js -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
{% endblock%}

<!DOCTYPE html>

{% block container %}
<div class="container col-sm-12 col-md-6">
    <div class="d-flex justify-content-center align-items-center">
        {% include "posts/posts_card.html" %}
    </div>
    <form class="bg-white container col-sm-12 col-md-10 pt-3 pb-3" style="margin-bottom: 1rem; margin-top: 1rem;" method="POST">
        {% csrf_token %}
        
        <div class=" bg-white row justify-content-center align-items-center  bg-light pb-2 pt-2 ">
            
            <div class="d-flex flex-row align-items-start mr-2">
                {% if  request.user.profile.picture%}
                    <img class ="rounded-circle mr-2" src="{{request.user.profile.picture.url}}" width="30" height="30" >
                {% else %}
                    <img class ="rounded-circle mr-2" src="{% static 'img/default-profile.png' %}" width="30" height="30" >
                {% endif %}
                
                <div>
                    {{ comment_form.body }}
                </div>   
            </div>
            <div class="d-flex align-items-endblock mt-2">
                <button class="btn btn-primary btn-sm shadow-none" type="submit">Post comment</button>
            </div>
           
        </div>
    </form>
   

    {% for comments in comment %}
        <div class="bg-white container col-sm-12 col-md-10">
            <div class="d-flex flex-row user-info">
                {% for users in users_filter %}
                    {% if users.username == comments.user.username%}
                        {% if users.profile.picture %}
                            <img class="rounded-circle mr-2" src="{{users.profile.picture.url}}" width="30" height="30" >                                    
                        {% else %}
                            <img class="rounded-circle mr-2" src="{% static 'img/default-profile.png' %}" width="30" height="30" >                                    
                            
                        {% endif %}
                    {% endif %}
                
                {% endfor %}
                <a href="{% url 'users:detail' comments.user.username %}" style="text-decoration: none;">
                    <div class="d-flex flex-column justify-content-start ml-2">
                        <span class="d-block font-weight-bold name">{{comments.user.username}}</span>
                        <span class="date text-black-50"> {{comments.date}}</span>
                    </div>
                </a>
            </div>
            <div class="mt-2 mb-2 d-flex justify-content-between ">
                <p class="comment-text">{{ comments.body }}</p>
                {% if user == comments.user%}
                        <ul class="navbar-nav ">
                            <li class="nav-item dropdown">
                                <a class="nav-link p-0" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-ellipsis-h" style="color: gray;"></i>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{% url 'posts:commentUpdate' post.pk comments.pk %}">Edit</a>
                                    <a class="dropdown-item" href="{% url 'posts:commentDelete' post.pk comments.pk %}">Delete</a>
                                </div>
                            </li>
                        </ul>
                {% endif %}
                {% if user == post.user and not user == comments.user%}
                        <ul class="navbar-nav ">
                            <li class="nav-item dropdown">
                                <a class="nav-link p-0" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-ellipsis-h" style="color: gray;"></i>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{% url 'posts:commentDelete' post.id comments.id %}">Delete</a>
                                </div>
                            </li>
                        </ul>
                {% endif %}
                
                
            </div>
        </div>
    {% endfor %}

    



</div>
{% endblock %}

templates/posts/feed.html
{% extends "base.html" %} {% comment %} Aqui especificamos de que template heredará los elementos 
e inyectará lo definido en este apartado, como si tomara una plantilla para renderizar. {% endcomment %}
{% load static %}


{% block head_content %} {% comment %} Actuan como si se definieran clases. {% endcomment %}
    <title>Platzigram feed</title>
    <script src="https://kit.fontawesome.com/d2b20da030.js" crossorigin="anonymous"></script>
{% endblock  %}

{% block container %} {% comment %} Apartado para desplegar los posts creados por los usuarios. {% endcomment %}
    <div class="container col-sm-12 col-md-6"> {% comment %} las "class" es sintaxis de "BOOTSTRAP", {% endcomment %}
        <div class="row d-flex justify-content-center ">
            {% for post in post %}  
                <div class="d-block col-sm-12 col-md-10 post-container ">
                    <div class="media pt-3 pl-3 pb-1"> 
                        <a href="{% url "users:detail" post.user.username %}">
                            {% if post.profile.picture %}
                                <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}" >
                            {% else %}
                                <img class="mr-3 rounded-circle" height="35" src="{% static 'img/default-profile.png' %}" alt="{{ post.user.get_full_name }}" >
                            {% endif %}
                        </a>
                        <div class="media-body">
                            <p style="margin-top:5px;">{{ post.user.get_full_name }}</p>
                        </div>
                    </div>
                    <a href="{% url "posts:detailPost" post.id %}">
                        <img  style="width: 100%; height: 400px; object-fit: cover;" src="{{ post.photo.url }}" alt="{{ post.title }}">
                    </a>
                    <p class="mt-1 mb-1 ml-2">
                        <a href="{% url "posts:postLike" post.id %}" class="text-decoration-none" style="color: #000; font-size: 30px;">
                            {% if post.id in liked_posts %}
                                <i class="fas fa-heart text-danger"> </i> 
                            {% else %}
                                <i class="far fa-heart"> </i>
                            {% endif %}
                            <i class="bi bi-check-circle"></i> 
                        </a> 
                        <!-- Icono de mensaje -->
                        <a href="{% url "posts:detailPost" post.id %}">
                            <i class="fa-regular fa-comment ml-2" style="color: #000; font-size: 30px;"></i>
                        </a> 
                    </p>
                    <strong class="ml-2">{{post.likes}} {% if post.likes != 1  %}likes{%else%}like{% endif %} </strong>
                    {% with username=post.user.username %}
                    {% for key, value in comment_counts.items %}
                        {% if post.id == key %}
                            {#{{ key }} :#} <strong class="ml-2">{{value}}</strong>
                            <strong>{% if value != 1  %}Comments{%else%}Comment{% endif %}</strong>
                            {% if value >= 1 %}
                                <a class="" style="color: #000" href="{% url "posts:detailPost" post.id %}">
                                    More...
                                </a> 
                            {% else %}
                                <a class="" style="color: #000" href="{% url "posts:detailPost" post.id %}">
                                    Post comment...
                                </a> 
                            {% endif %}
                        {%endif%}
                    {% endfor %}
                    {% endwith %}
                    <p class="ml-2 mt-0 mb-2">
                        <strong>@{{post.user.username}}</strong>-<h7>{{post.title}}</h7> - <small>{{post.created}}</small>
                    </p>
                </div>
            {% endfor %}
        </div>
    </div>
    {% include "pagination.html" %}
{% endblock %}

templates/posts/posts_card.html
{% load static %}

{% block head_content %}    
    <script src="https://kit.fontawesome.com/d2b20da030.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <!-- jQuery y Popper.js -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% endblock  %}

<div class="d-block col-sm-12 col-md-10 post-container ">
    <div class="media pt-3 pl-3 pb-1 justify-content-between">   
        <a href="{% url "users:detail" post.user.username %}">
            {% if post.profile.picture %}
                <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}" >
            {% else %}
                <img class="mr-3 rounded-circle" height="35" src="{% static 'img/default-profile.png' %}" alt="{{ post.user.get_full_name }}" >
            {% endif %}     
        </a>
        <div class="media-body">
            <p style="margin-top:5px;">{{ post.user.get_full_name }}</p>
        </div>
        {% if user == request.user %}   
                <ul class="navbar-nav mr-2">
                    <li class="nav-item dropdown">
                        <a class="nav-link p-0" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-h" style="color: gray;"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'posts:postUpdate' post.id %}">Edit</a>
                            <a class="dropdown-item" href="{% url 'posts:postDelete' post.id %}">Delete</a>
                        </div>
                    </li>
                </ul>
        {% endif %}
    </div>
    <a href="{% url "posts:detailPost" post.id %}">
        <img  style="width: 100%; height: 400px; object-fit: cover;" src="{{ post.photo.url }}" alt="{{ post.title }}">
    </a>
    {#<h6 class="ml-1 mt-1">{{ post.title }}</h6> #}
    <p class="mt-1 mb-1 ml-2">
        <a href="{% url "posts:postLike" post.id %}" class="text-decoration-none" style="color: #000; font-size: 30px;">
            {% if post.id in liked_posts %}
                <i class="fas fa-heart text-danger"> </i> 
            {% else %}
                <i class="far fa-heart"> </i>
            {% endif %}
            <i class="bi bi-check-circle"></i> 
        </a> 
        <!-- Icono de mensaje -->
        <a href="{% url "posts:detailPost" post.id %}">
            <i class="fa-regular fa-comment ml-2" style="color: #000; font-size: 30px;"></i>
        </a> 
    </p>
    <strong class="ml-2">{{post.likes}} {% if post.likes != 1  %}likes{%else%}like{% endif %} </strong>
    <strong class="ml-2">{{comment_count}} {% if comment_count != 1  %}Comments{%else%}Comment{% endif %} </strong>
    <p class="ml-2 mt-0 mb-2">
        <strong>@{{post.user.username}}</strong>-<h7>{{post.title}}</h7> - <small>{{post.created}}</small>
    </p>
</div>