directs/urls.py
"""Directs URLs."""

# Django
from django.urls import path

# Views
# Aqui se habia definido como as post_views. Pero ya no es necesario.
from directs import views

urlpatterns = [
    # Managment
    path(
        route='inbox/',
        view=views.inbox,
        name='message'
    ),  # Agregaremos una vista de la app "directs" para el inbox

    path(
        route='directs/<str:username>/',
        view=views.directs,
        name='direct'
    ),  # Agregaremos una vista de la app "directs" para chat personal

    path(
        route='send/',
        view=views.SendMessage,
        name='sendMessage'
    ),  # Agregaremos una vista de la app "directs" para enviar mensajes

    path(
        route='search/',
        view=views.UserSearch,
        name='userSearch'
    ),  # Agregaremos una vista de la app "directs" para buscar un usuario

    path(
        route='new/<str:username>',
        view=views.NewMessage,
        name='newMessage'
    ),  # Agregaremos una vista de la app "directs" para crear un nuevo mensajes

    path(
        route='delete/<str:username>',
        view=views.DeleteMessage,
        name='deleteMessage'
    ),  # Agregaremos una vista de la app "directs" para eliminar conversacion actual.

]

notifications/urls.py
"""Notifications URLs."""

# Django
from django.urls import path

# Views
from notifications import views

urlpatterns = [

    # Managment
    path(
        route='',
        view=views.ShowNotifications,
        name='showNotifi'
    ),  # Agregamos la vista para ver las notificaciones de la app "Notifications"

    path(
        route='delete/<int:noti_id>',
        view=views.DeleteNotifications,
        name='deleteNotifi'
    ),
]

platzigram/urls.py
# Django
from django.contrib import admin
from django.conf import settings # Importamos la libreria de "settings" para poder mostrar imagenes.
from django.conf.urls.static import static # Libreria para poder serviri imagenes en desarrollo.
from django.urls import path, include
# urls.py
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include(('posts.urls','posts'), namespace='posts')), # En la tupla incluimos al modulo "posts.urls" y la app "posts".
    path('users/', include(('users.urls','users'), namespace='users')), # En la tupla incluimos al modulo "users.urls" y la app "users".
    path('comment/', include(('comment.urls','comment'), namespace='comment')), # En la tupla incluimos al modulo "comment.urls" y la app "comment".
    path('message/', include(('directs.urls','directs'), namespace='directs')), # En la tupla incluimos al modulo "directs.urls" y la app "directs".
    path('notifications/', include(('notifications.urls','notifications'), namespace='notifications')), # En la tupla incluimos al modulo "notifications.urls" y la app "notifications".
    
    
    #Password reset
    path(route='password_reset/', view=auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
# Aqui se habia definido como as post_views. Pero ya no es necesario.
from posts import views

urlpatterns = [

    # Managment
    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),  # Agregaremos una vista de la app "posts"

    path(
        route='posts/new',
        view=views.CreatePostView.as_view(),
        name="create"
    ),  # Agregamos la vista para crear un nuevo post.

    # Solucion del reto por parte del profe

    path(
        route='posts/<int:pk>/',  # post.id, pk
        view=views.PostDetailView.as_view(),
        name='detailPost'
    ),

    path(
        route='posts/<int:post_id>/like',
        view=views.LikesView,
        name="postLike"
    ),

    path(
        route='posts/<int:post_id>/update',
        view=views.UpdatePostView.as_view(),
        name="postUpdate"
    ),

    path(
        route='posts/<int:pk>/delete',
        view=views.PostDeleteView.as_view(),
        name="postDelete"
    ),

    path(
        route='posts/<int:pk>/<int:id>/comment_delete',
        view=views.DeleteCommentView.as_view(),
        name="commentDelete"
    ),

    path(
        route='posts/<int:post_pk>/<int:comments_id>/update_comment',
        view=views.UpdateCommentView.as_view(),
        name="commentUpdate"
    ),

]

users/urls.py
"""Users URLs."""

# Django
from django.urls import path


# Views
# Aqui se habia definido como as user_views. Pero ya no es necesario.
from users import views

urlpatterns = [
    
    # Managment
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),  # Agregamos la vista para ingresar a la app.
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),  # Agregamos la vista para salir de la app.
    path(
        route='signup/',
        view=views.SignUpView.as_view(),
        name="signup"
    ),  # Agregamos la vista para registrarse en la app.
    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name="update"
    ),  # Agregamos la vista para modificar nuestro perfil.

    path(
        route='me/profile/delete_photo',
        view=views.delete_picture,
        name="deletePicture"
    ),  # Agregamos la vista para eliminar nuestra foto de perfil.

    # Posts
    path(
        route='profile/<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    path(
        route='profile/<str:username>/follow',
        view=views.FollowView,
        name="follow"
    ),

    path(
        route='profile/<str:username>/followers',
        view=views.FollowerView.as_view(),
        name="followers"
    ),

    path(
        route='profile/<str:username>/following',
        view=views.FollowingView.as_view(),
        name="following"
    ),

    path(
        route='me/profile/delete_profile',
        view=views.delete_user,
        name="deleteUser"
    )  # Agregamos la vista para eliminar nuestro perfil y usuario.



]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <script src="https://kit.fontawesome.com/d2b20da030.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <!-- jQuery y Popper.js -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    
</head>
<body>

    {% include "nav.html" %}
    <div class="container mt-5 pt-4">
        {% block container %}
        {% endblock%}
    </div>

</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">    
        {#Feed button.#}
        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url "posts:feed" %}">
            <img src="{% static "img/instagram.png" %}" height="45" class="d-inline-block align-top"/>
        </a>
        <div class="">
            <ul class="navbar" id="profile-section">
                {#Profile button.#}
                <li class="nav-item">
                    <a href="{% url "users:detail" request.user.username %}">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% else %}
                            <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>
                {#Create post button.#}
                <li class="nav-item nav-icon">
                    <a href="{% url "posts:create" %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>
                {#logout button.#}
                <li class="nav-item nav-icon"> 
                    <a href="{% url "users:logout" %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>
            </ul>
            {#Search modo#}
        </div >
        <form action="{% url 'directs:userSearch' %}" method="GET" >
            <div class="headedr__search">
                <input type="text" placeholder="Search Account" name="q" value="{{ request.GET.q }}" required>
                <button class="btn btn-primary" type="submit">Search</button>
            </div>
        </form>
        <li class="nav-item nav-icon position-relative " id="message-icon" style="list-style: none;">
            <a href="{% url "directs:message" %}" >
                <i class="fa-regular fa-comments " style="font-size: 2.2rem;"></i>
                {% if unread_notifi %}
                    <strong class="position-absolute top-0 start-70 translate-middle badge rounded-pill bg-danger fs-10" style="font-size: .7rem;">
                        {{unread_notifi}}
                    </strong>
                {% endif %}
            </a>
        </li>
        {# Notificacion de likes, follows, comments #}
        <li class="nav-item nav-icon position-relative "  style="list-style: none;">
            <a href="{% url "notifications:showNotifi" %}" >
                <i class="fa-regular fa-bell " style="font-size: 2.2rem;"></i>
                {% if count_notifications %} 
                    <strong class="position-absolute top-0 start-70 translate-middle badge rounded-pill bg-danger fs-10" style="font-size: .7rem;">
                        {{count_notifications}}
                    </strong>
                {% endif %}
            </a>
        </li>        
    </div>
</nav>

templates/pagination.html
{#Paginacion.#}
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>