directs/urls.py
"""Directs URLs."""

# Django
from django.urls import path

# Views
# Aqui se habia definido como as post_views. Pero ya no es necesario.
from directs import views

urlpatterns = [
    # Managment
    path(
        route='inbox/',
        view=views.inbox,
        name='message'
    ),  # Agregaremos una vista de la app "directs" para el inbox

    path(
        route='directs/<str:username>/',
        view=views.directs,
        name='direct'
    ),  # Agregaremos una vista de la app "directs" para chat personal

    path(
        route='send/',
        view=views.SendMessage,
        name='sendMessage'
    ),  # Agregaremos una vista de la app "directs" para enviar mensajes

    path(
        route='search/',
        view=views.UserSearch,
        name='userSearch'
    ),  # Agregaremos una vista de la app "directs" para buscar un usuario

    path(
        route='new/<str:username>',
        view=views.NewMessage,
        name='newMessage'
    ),  # Agregaremos una vista de la app "directs" para crear un nuevo mensajes

    path(
        route='delete/<str:username>',
        view=views.DeleteMessage,
        name='deleteMessage'
    ),  # Agregaremos una vista de la app "directs" para eliminar conversacion actual.

]

platzigram/urls.py
# Django
from django.contrib import admin
from django.conf import settings # Importamos la libreria de "settings" para poder mostrar imagenes.
from django.conf.urls.static import static # Libreria para poder serviri imagenes en desarrollo.
from django.urls import path, include
# urls.py
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include(('posts.urls','posts'), namespace='posts')), # En la tupla incluimos al modulo "posts.urls" y la app "posts".
    path('users/', include(('users.urls','users'), namespace='users')), # En la tupla incluimos al modulo "users.urls" y la app "users".
    path('comment/', include(('comment.urls','comment'), namespace='comment')), # En la tupla incluimos al modulo "comment.urls" y la app "comment".
    path('message/', include(('directs.urls','directs'), namespace='directs')), # En la tupla incluimos al modulo "directs.urls" y la app "directs".
    path('notifications/', include(('notifications.urls','notifications'), namespace='notifications')), # En la tupla incluimos al modulo "notifications.urls" y la app "notifications".
    
    
    #Password reset
    path(route='password_reset/', view=auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
# Aqui se habia definido como as post_views. Pero ya no es necesario.
from posts import views

urlpatterns = [

    # Managment
    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),  # Agregaremos una vista de la app "posts"

    path(
        route='posts/new',
        view=views.CreatePostView.as_view(),
        name="create"
    ),  # Agregamos la vista para crear un nuevo post.

    # Solucion del reto por parte del profe

    path(
        route='posts/<int:pk>/',  # post.id, pk
        view=views.PostDetailView.as_view(),
        name='detailPost'
    ),

    path(
        route='posts/<int:post_id>/like',
        view=views.LikesView,
        name="postLike"
    ),

    path(
        route='posts/<int:post_id>/update',
        view=views.UpdatePostView.as_view(),
        name="postUpdate"
    ),

    path(
        route='posts/<int:pk>/delete',
        view=views.PostDeleteView.as_view(),
        name="postDelete"
    ),

    path(
        route='posts/<int:pk>/<int:id>/comment_delete',
        view=views.DeleteCommentView.as_view(),
        name="commentDelete"
    ),

    path(
        route='posts/<int:post_pk>/<int:comments_id>/update_comment',
        view=views.UpdateCommentView.as_view(),
        name="commentUpdate"
    ),

]

users/urls.py
"""Users URLs."""

# Django
from django.urls import path


# Views
# Aqui se habia definido como as user_views. Pero ya no es necesario.
from users import views

urlpatterns = [
    
    # Managment
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),  # Agregamos la vista para ingresar a la app.
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),  # Agregamos la vista para salir de la app.
    path(
        route='signup/',
        view=views.SignUpView.as_view(),
        name="signup"
    ),  # Agregamos la vista para registrarse en la app.
    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name="update"
    ),  # Agregamos la vista para modificar nuestro perfil.

    path(
        route='me/profile/delete_photo',
        view=views.delete_picture,
        name="deletePicture"
    ),  # Agregamos la vista para eliminar nuestra foto de perfil.

    # Posts
    path(
        route='profile/<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    path(
        route='profile/<str:username>/follow',
        view=views.FollowView,
        name="follow"
    ),

    path(
        route='profile/<str:username>/followers',
        view=views.FollowerView.as_view(),
        name="followers"
    ),

    path(
        route='profile/<str:username>/following',
        view=views.FollowingView.as_view(),
        name="following"
    ),

    path(
        route='me/profile/delete_profile',
        view=views.delete_user,
        name="deleteUser"
    )  # Agregamos la vista para eliminar nuestro perfil y usuario.



]

users/forms.py
"""Users forms."""

# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile


class SignupForm(forms.Form):
    """Sign up form."""
    username = forms.CharField(min_length=4, max_length=50)
    password = forms.CharField(max_length=70, widget=forms.PasswordInput())
    password_confirmation = forms.CharField(
        max_length=70, widget=forms.PasswordInput())
    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)
    email = forms.CharField(min_length=6, max_length=30,
                            widget=forms.EmailInput())
    """Antes de pasar el dato del username, primero lo limpearemos"""

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        else:
            
            return username

    """Lo mismo aremos para el email."""

    def clean_email(self):
        """Email must be unique."""
        email = self.cleaned_data['email']
        email_taken = User.objects.filter(email=email).exists()
        if email_taken:
            raise forms.ValidationError('Email is already in use.')
        else:
            
            return email
    """La comparacion de elementos del mismo "form" se hacen en orden y este se ejecuta al final"""

    def clean(self):
        """Verify password confimation match"""
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Password do not match.')
        else:
            
            return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        # Excluimos un dato (no esta definido en nuestro modelo).
        data.pop('password_confirmation')
        # Podriamos enviar como (email=data['email'],..) |(**data) envía.todos.los.datos.
        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

users/views.py
"""Users views."""
# Django.
from typing import Any
# Importamos las librerias para un ingreso correcto.
from django.contrib.auth import logout
# Importamos al decorador "login_r.."para evitar logout repentino.
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Importamos una vista generica para utulizar "Authenticate"
from django.contrib.auth import views as auth_views
from django.db.models.base import Model as Model
# Redirect solo acepta valores ".html" o sus "names".
from django.shortcuts import render, redirect, get_object_or_404
# Modulo para crear clases de view.
from django.views.generic import DetailView, FormView, UpdateView
from django.urls import reverse, reverse_lazy  # Modulo para crear URLS.
from django.http import HttpResponseRedirect

# Forms
from users.forms import SignupForm

# Models
from django.contrib.auth.models import User
from posts.models import Post
from users.models import Profile, Follow


# Create your views here.

class UserDetailView(LoginRequiredMixin, DetailView):
    """User detail view. Independientemente si es propio o de otro usuario
    se crea una clase ya que la logica que se va a utilizar es un poco mas robusta."""
    login_url = 'users:login'  # En dado caso de que ingresemos sin usuario nos redireccionará.
    template_name = 'users/detail.html'
    # Actua como una PK ya que no hay usuarios repetidos.
    slug_field = 'username'
    # Es el valor que se le agergará en cada campo al buscar un perfil.
    slug_url_kwarg = 'username'
    # Aqui importamos todos los datos de usuairos y procesarlos segun la accion.
    queryset = User.objects.all()
    # Este será el nombre del objeto que manejaremos en las templates.
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context."""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        follower = self.request.user  # Corresponde al following_update
        
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        context['posts_count'] = Post.objects.filter(user=user).count()
        context['following_count'] = Follow.objects.filter(
            follower=user).count()
        context['followers_count'] = Follow.objects.filter(
            following=user).count()
        context['following_update'] = Follow.objects.filter(
            follower=follower, following=user).count()
        context['unread_notifi'] = self.request.unread_notifi
        
        return context


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update profile view."""
    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']

    def get_object(self):
        """Regresamos el usuario del Perfil actual, esto para armar una "URL compuesta"."""
        return self.request.user.profile

    def get_success_url(self):
        """Creamos la "URL" con el nombre de usuario obtenido mediante self."""
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username': username})

    def get_context_data(self, **kwargs):
        """Add user's posts to context."""
        context = super().get_context_data(**kwargs)
        context['unread_notifi'] = self.request.unread_notifi
        return context


@login_required
def delete_user(request):
    user = request.user

    if request.method == 'POST':
        # Eliminar el usuario
        user.delete()
        logout(request)
        return redirect('users:login') 
    
    context = {'unread_notifi': request.unread_notifi}
    
    return render(request, 'users/delete_user.html', context)


@login_required
def delete_picture(request):
    user = request.user
    
    if request.method == "POST":
        if user.profile.picture:
            user.profile.picture.delete()
            
        return redirect("users:update")
 
    context = {'unread_notifi': request.unread_notifi}

    return render(request, 'users/delete_picture.html', context)


class SignUpView(FormView):
    """Users sign up. Utilizando "FromView" """
    redirect_field_name = 'posts:feed'
    redirect_authenticated_user = True
    template_name = "users/signup.html"
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)


class LoginView(auth_views.LoginView):
    """Login view."""
    template_name = 'users/login.html'
    redirect_authenticated_user = True


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""
    template_name = 'users/logged_out.html'  # Esta direccion no será requerida para el proceso pero si para declarar la funcion.


@login_required
def FollowView(request, username):
    user = request.user  # Usuario logeado
    # Traemos al modelo user del usuario visitado
    following = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(follower=user, following=following).count()
    if not follow:
        follow = Follow.objects.create(follower=user, following=following)
        # follow.save() #no se guarda porque crea dos parametros
    else:
        follow = Follow.objects.filter(
            follower=user, following=following).delete()

    return HttpResponseRedirect(reverse('users:detail', args=[username]))


""" #def FollowersView(request, username):

    ###user_loged = request.user #Usuario logeado actualmente
    #user = get_object_or_404(User, username=username) #Usuario del perfil que estamos viendo
    #followers_filter_names = Follow.objects.filter(following=user) #Filtramos para buscar quienes siguen a nuestro usuario actual
    #followers_names = [names.follower.username for names in followers_filter_names]
    #followers_names = sorted(followers_names)
    ###print(followers_names)

    #########
    #context = {
    #    'followers_names': followers_names,
    #    'user': user
    #}
    #return render(request, 'users/followers.html',  context) """


class FollowerView(LoginRequiredMixin, DetailView):
    """User detail view. Independientemente si es propio o de otro usuario
    se crea una clase ya que la logica que se va a utilizar es un poco mas robusta."""
    login_url = 'users:login'  # En dado caso de que ingresemos sin usuario nos redireccionará.
    template_name = 'users/followers.html'
    # Actua como una PK ya que no hay usuarios repetidos.
    slug_field = 'username'
    # Es el valor que se le agergará en cada campo al buscar un perfil.
    slug_url_kwarg = 'username'
    # Aqui importamos todos los datos de usuairos y procesarlos segun la accion.
    queryset = User.objects.all()
    # Este será el nombre del objeto que manejaremos en las templates.
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context."""
        context = super().get_context_data(**kwargs)
        user = self.get_object()

        # Filtramos para buscar quienes siguen a nuestro usuario actual
        followers_filter_names = Follow.objects.filter(following=user)
        followers_names = [
            names.follower.username for names in followers_filter_names]
        followers_names = sorted(followers_names)

        # Obtenemos los modelos con la lista obtenida anteriormente.
        users_filter = User.objects.filter(username__in=followers_names)
        # print(users_filter)
        context['users_filter'] = users_filter

        return context


class FollowingView(LoginRequiredMixin, DetailView):  # Clase de la view Following
    login_url = 'users:login'
    template_name = 'users/following.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        # Filtramos para buscar quienes siguen a nuestro usuario actual
        following_filter_names = Follow.objects.filter(follower=user)
        # Obtenemos una lista de nombres
        following_names = [
            names.following.username for names in following_filter_names]
        following_names = sorted(following_names)  # Ordenamos los datos
        # Obtenemos los modelos con la lista obtenida anteriormente.
        users_filter = User.objects.filter(username__in=following_names)

        context['users_filter'] = users_filter

        return context


""" def FollowingView(request, username):
    user = get_object_or_404(User, username=username) #Usuario del perfil que estamos viendo
    following_filter_names = Follow.objects.filter(follower=user) #Filtramos para buscar quienes siguen a nuestro usuario actual
    following_names = [names.following.username for names in following_filter_names]
    following_names = sorted(following_names)
    print(following_names)
    
    #########
    context = {
        'following_names': following_names,
        'user': user
    }
    return render(request, 'users/following.html',  context) """

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body class="h-100">
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>
</body>
</html>

templates/users/delete_picture.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
    <title>@{{ request.user.username }} | Delete profile photo</title>
{% endblock  %}

{% block container %}

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6 pt-3 pb-3" id="profile-box">
            <h5 class="card-title">Delete profile photo?</h5>
            <p class="card-text">Deleting a profile photo will permanently delete it from the database.</p>
            <form class='col-md-12  d-flex justify-content-between ' method="POST" action="{% url 'users:deletePicture' %}">
                {% csrf_token %}
                <a class="btn btn-primary" href="{% url "users:update" %}">Keep Post</a>
                <button type="submit" class="btn btn=primary btn-danger">Delete Profile Picture</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/users/detail.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
    <title>@{{ user.username }} | Detail user</title>
{% endblock %}

{% block container %}
    <div class="container mb-3" style="margin-top: 1em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                {% if user.profile.picture %}
                    <img src="{{ user.profile.picture.url }}" alt="{{ user.username}}" class="rounded-circle" width="150px" height="150px" />
                {% else %}
                    <img src="{% static 'img/default-profile.png' %}" alt="{{ user.username}}" class="rounded-circle" width="150px" height="150px" />
                {% endif %}
            </div>
            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    <strong>
                        {{user.first_name|title }} {{user.last_name|title }}
                    </strong>
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        {% if following_update %}
                            <a
                                href="{% url "users:follow" user.username %}"
                                class="ml-5 btn btn-sm btn-primary btn-danger"
                            >
                                Unfollow
                            </a>
                        {% else %}
                            <a
                                href="{% url "users:follow" user.username %}"
                                class="ml-5 btn btn-sm btn-primary"
                            >
                                Follow
                            </a>
                        {% endif %}    
                    {% endif %}
            
                    {% if user != request.user %}       
                        <a
                            href="{% url "directs:newMessage" user.username %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Message
                        </a>
                    {% endif %}
                </h3>
                <strong>@{{ user.username }}</strong>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>◉ {{ posts_count }}</b> posts
                    </div>
                    <div class="col-sm-4">
                        <a href="{% url "users:followers" user.username %}" style=" text-decoration: none;">
                            <b>◉ {{ followers_count }}</b> followers
                        </a>
                    </div>
                    <div class="col-sm-4">
                        <a href="{% url "users:following" user.username %}" style=" text-decoration: none;">
                            <b>◉ {{ following_count }}</b> following
                        </a>
                    </div>
                </div>
                <hr>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        {% if  user.profile.website%}
                            <strong><a href="{{user.profile.website}}" target="_blank" style=" text-decoration: none;">◉ {{ user.profile.website }} </a></strong>   
                        {% endif %}
                        {% if  user.profile.biography%}
                            <hr>      
                            <p>◉ {{ user.profile.biography }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>
    {#Apartado para mostrar los posts.#}
    <div class="container" id="user-posts">
        <div class="row mt-1 ">
            {% for post in posts %}         
                <div class="col-sm-4 pt-0 pb-3  pr-3 pl-3 d-flex flex-column justify-content-center align-items-center">
                    {#<a href="{% url 'users:detailPost' request.user.username post.id %}" class="border">#}
                    {% if user == request.user %}   
                        <ul class="navbar-nav ">
                            <li class="nav-item dropdown">
                                <a class="nav-link p-0" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-ellipsis-h" style="color: gray;"></i>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{% url 'posts:postUpdate' post.id %}">Edit</a>
                                        <a class="dropdown-item" href="{% url 'posts:postDelete' post.id %}">Delete</a>
                                </div>
                            </li>
                        </ul>
                    {% endif %}
                    <a href="{% url 'posts:detailPost' post.id %}" class="border">
                        <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"  style="width: 400px; height: 300px; object-fit: cover;"/>
                    </a>
                </div>   
                {% endfor %}
        </div>
    </div>
{% endblock %}

templates/users/login.html
{% extends "users/base.html" %} {% comment %} Importamos la plantilla a utilizar.  {% endcomment %}

{% block head_content %}
    <title>Platzigram sign in</title>
{% endblock  %}

{% block container %}
    {% if form.errors %}
        <p class="alert alert-danger">Your username and password didn't match. Please try again.</p>
    {% endif  %}
    <form method="POST" action="{% url "users:login" %}">
        
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control mb-2" type="text" placeholder="Username" name="username" />
        </div>
        <div class="form-group">
            <input class="form-control" type="password" placeholder="Password" name="password" />
        </div>
        <button class="btn btn-primary btn-block mt-5" type="submit">Sign in</button>

    </form>
    <p class="mt-4">Don't have an account yet?<a href="{% url "users:signup" %}"> Sign up here.</a></p>
    <p>Forgot your password? <a href="{% url 'password_reset' %}">Reset it here.</a></p>
    
{% endblock  %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>Platzigram sign up</title>
{% endblock  %}

{% block container %}
    <form action="{% url 'users:signup' %}" method='POST'>
        
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-block mt-5" type="submit">Register</button>

    </form>
{% endblock  %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
    <title>@{{ request.user.username }} | Update profile</title>
{% endblock  %}

{% block container %}
    <div class="container">
        <div class="row justify-content-md-center" style="margin-top: -1em;">
            <div class="col-6 p-4 " id="profile-box">
                <form action= "{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
                    
                    {% csrf_token %}
                    {% if messages %}
                        <ul class="messages list-unstyled">
                            {% for message in messages %}
                                <li  {% if message.tags %} class="alert alert-success {{ message.tags }} " {% endif %}> {{ message }} </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <div class='media'>
                        {% if profile.picture %}
                            <img src="{{ profile.picture.url }}" class="rounded-circle" height="50"/>
                        {% else %}
                            <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50"/>
                        {% endif %}
                        <div class="media-body">
                            <h5 class="ml-4">@{{ user.username }} | {{user.get_full_name}}</h5>
                            <p class="ml-4">
                                <input type="file" name="picture" >
                            </p>
                            {% if profile.picture %}
                                <a class="ml-4 mt-0 btn btn-primary btn-danger" href="{% url "users:deletePicture" %}">Delete profile picture.</a>
                            {% endif %}
                        </div>
                    </div>
                    {# Error picture.#}
                    {% for error in form.picture.errors  %}
                        <div class="alert alert-danger">
                            <strong>Picture: </strong>{{ error }}
                        </div>
                    {% endfor %}
                    <hr>
                    {# Website field. #}
                    <div class="form-group">
                        <label>Website</label>
                        <input 
                            class="form-control {% if form.website.errors %}is-invalid{% endif %}" 
                            type="text" 
                            name="website" 
                            placeholder="Website"
                            value="{% if form.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}"
                        />
                        <div class="invalid-feedback">
                            {% for error in form.website.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    {# Biography field. #}
                    <div class="form-group">
                        <label>Biography</label>
                        <textarea 
                            class="form-control {% if form.biography.errors %}is-invalid{% endif %}" 
                            name="biography"
                            >{% if form.errors %}{{form.biography.value}}{% else %}{{ profile.biography }}{% endif %}
                        </textarea>
                        <div class="invalid-feedback">
                            {% for error in form.biography.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    {# Phone number field. #}
                    <div class="form-group">
                        <label>Phone number</label>
                        <input
                            class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                            type="text"
                            name="phone_number"
                            placeholder="Phone number"
                            value="{% if form.errors %}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}"
                        />
                        <div class="invalid-feedback">
                            {% for error in form.phone_number.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row justify-content-md-center">
                        <button type="submit" class="btn btn-primary btn-block mt-3">Update info</button>
                        <a class=" mt-1 btn btn-primary btn-danger" href="{% url "users:deleteUser"%}">Delete profile.</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}